- name: Variables
  hosts: local
  connection: local
  vars: # play level variables
    COURSE: "DevOps with AWS"
    DURATION: 120HRS
    TRAINER: shivakumar
  tasks: 
    - name: print the variables
      vars: # task level variables
        COURSE: Ansible
      ansible.builtin.debug:
        msg: "course is {{ COURSE }}, Duration is {{ DURATION }}, Traininer is {{ TRAINER }}"

  - name: print the variables1  
    ansible.builtin.debug:
        msg: "course is {{ COURSE }}, Duration is {{ DURATION }}, Traininer is {{ TRAINER }}"   