- name: variables from files
  hosts: local
  connection: local
  vars_prompt:
  - name: COURSE
    prompt: Please enter course name
  - name: DURATION
    prompt: please enter duration
  - name: TRAINER
    prompt: please enter trainer name    
  tasks: 
  - name: print course information
    ansible.builtin.debug:
      msg: "course is {{ COURSE }}, Duration is {{ DURATION }}, Traininer is {{ TRAINER }}" 