- name: Variables
  hosts: local
  connection: local
  vars: # play level variables
    GREET: "PLAY"
  vars_files:
  - course.yaml 
  vars_prompt:
  - name: GREET
    prompt: Enter the value
    private: false
  tasks: 
  - name: print the variables
    vars: 
      GREET: "TASK"
  - name: print the variable
    ansible.builtin.debug:
      msg:"Hello from {{ GREET }}"